### ISSUE TITLE
Game crash when trying to enter the estate

### ISSUE THREAD

**Issue by loonaticx** [open-toontown/open-toontown#48]
# Explanation

Trying to go to your estate as a new toon will crash your game.

# Output + Example

```
Traceback (most recent call last):
  File "G:\Work Folder\Toontown\dev\forks\open-toontown\otp\launcher\LauncherBase.py", line 152, in mainLoop
    self._runTaskManager()
  File "G:\Work Folder\Toontown\dev\forks\open-toontown\otp\launcher\LauncherBase.py", line 132, in _runTaskManager
    taskMgr.run()
  File "C:\Panda3D-1.11.0-opentoontown\direct\task\Task.py", line 540, in run
    self.step()
  File "C:\Panda3D-1.11.0-opentoontown\direct\task\Task.py", line 494, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-opentoontown\direct\showbase\ShowBase.py", line 2090, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.11.0-opentoontown\direct\interval\IntervalManager.py", line 95, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.11.0-opentoontown\direct\interval\IntervalManager.py", line 131, in __doPythonCallbacks
    self.MyEventmanager.doEvents()
  File "C:\Panda3D-1.11.0-opentoontown\direct\showbase\EventManager.py", line 44, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-opentoontown\direct\showbase\EventManager.py", line 100, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-opentoontown\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-opentoontown\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "G:\Work Folder\Toontown\dev\forks\open-toontown\toontown\toon\Toon.py", line 1844, in finishTeleportOut
    callback(*extraArgs)
  File "G:\Work Folder\Toontown\dev\forks\open-toontown\toontown\safezone\Playground.py", line 610, in __teleportOutDone
    self.getEstateZoneAndGoHome(requestStatus)
  File "G:\Work Folder\Toontown\dev\forks\open-toontown\toontown\hood\Place.py", line 645, in getEstateZoneAndGoHome
    base.cr.estateMgr.getLocalEstateZone(base.localAvatar.getDoId())
AttributeError: 'ToontownClientRepository' object has no attribute 'estateMgr'
Press any key to continue . . .
```

https://youtu.be/kR4BnjcMy2Q?t=298

# Steps to reproduce
1) Make a new toon, don't think it matters whether or not you choose to do the tutorial or not
2) Go into your sthickerbook and press "Go Home"

**Comment by loonaticx** [comment]
Bump

**Comment by DarthMDev** [comment]
I imagine this will be fixed when the estate AI is written.
