### ISSUE TITLE
Crash Lawbot

### ISSUE THREAD

**Issue by MiloCharmingMagician** [open-toontown/open-toontown#57]
16:11:40 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_lawbot_maps.bam: not found on model path (currently: "resources;/d/toontown/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")
:06-19-2022 16:11:41 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_lawbot_maps.bam: not found on model path (currently: "resources;/d/toontown/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")

**Comment by LuigiFan25** [comment]
Traceback and context?

**Comment by CyndaneraX** [comment]
> 

When I try to go into lawbot office, sellbot factory, etc. it crashes
and estate also crashes and minigame main menu crashes as well
I would like this to work plz, thanks.

**Comment by MiloCharmingMagician** [comment]
> Traceback and context?
AI Server

:07-20-2023 18:44:47 AIBase: __dev__ == True
:07-20-2023 18:44:47 AIBase: __astron__ == True
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:07-20-2023 18:44:48 ToontownAIRepository: Using connect method 'native'
DCFile::read of etc/otp.dc
DCFile::read of etc/toon.dc
:07-20-2023 18:44:48 ToontownAIRepository: Now connecting to 127.0.0.1:7199...
:07-20-2023 18:44:48 ToontownAIRepository: Connecting to gameserver directly (no proxy).
:07-20-2023 18:44:48 ToontownAIRepository: Connecting to //127.0.0.1:7199 via Native interface.
:07-20-2023 18:44:48 ToontownAIRepository: Connected successfully.
:07-20-2023 18:44:48 ToontownAIRepository: Generating district...
:07-20-2023 18:44:48 ToontownAIRepository: Declaring ownership...
:07-20-2023 18:44:48 ToontownAIRepository: Creating local objects...
:07-20-2023 18:44:48 ToontownAIRepository: Creating global objects...
:07-20-2023 18:44:48 ToontownAIRepository: Creating zones...
:07-20-2023 18:44:48 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 2200
:07-20-2023 18:44:48 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 2300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 13 in zone 3200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 13 in zone 3200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 16 in zone 3300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 42 in zone 4100
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 42 in zone 4100
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 57 in zone 4100
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 57 in zone 4100
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 19 in zone 4200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 25 in zone 4200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 25 in zone 4200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 48 in zone 4300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): Multiple front doors for building 28 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 9 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 9 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 10 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 15 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 35 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 36 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 37 in zone 5300
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): Multiple front doors for building 31 in zone 9100
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 31 in zone 9100
:07-20-2023 18:44:49 DistributedSuitPlannerAI: zone 11200 has 2 disconnected suit paths.
:07-20-2023 18:44:49 DistributedSuitPlannerAI: zone 12000 has 6 disconnected suit paths.
:07-20-2023 18:44:49 DistributedSuitPlannerAI: zone 13000 has 5 disconnected suit paths.
[<toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6605EE0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6605F40>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6613130>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B66132E0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6613490>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6613640>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B66137F0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B66139A0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x00000164B6613B50>] [golf_kart_0_0, golf_kart_0_1, golf_kart_0_2, golf_kart_1_0, golf_kart_1_1, golf_kart_1_2, golf_kart_2_0, golf_kart_2_1, golf_kart_2_2]
:07-20-2023 18:44:49 WelcomeValleyManagerAI: Creating Welcome Valley zones...
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 22200
:07-20-2023 18:44:49 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 22300
:07-20-2023 18:44:49 ToontownAIRepository: Done.
('Setting toonID ', 100000001)
DBB-addToon 100000001
:07-20-2023 18:46:46 DistributedBattleAI: battle done, resuming suit: 401003872
exit wait countdown
:07-20-2023 18:48:00 DistributedStageAI: generate 401003948, id=13300, floor=0
Traceback (most recent call last):
  File "H:\work\cyndanera\Projects\toontown\server\toontown\building\DistributedElevatorExtAI.py", line 144, in elevatorClosedTask
    self.elevatorClosed()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedLawOfficeElevatorExtAI.py", line 28, in elevatorClosed
    lawOfficeZone = self.bldg.createLawOffice(self.lawOfficeId, self.entranceId, players)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\LawOfficeManagerAI.py", line 47, in createLawOffice
    Stage.generateWithRequired(StageZone)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedStageAI.py", line 33, in generate
    room.generateWithRequired(self.zoneId)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedStageRoomAI.py", line 43, in generate
    typeReg = self.getEntityTypeReg()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\StageRoomBase.py", line 23, in getEntityTypeReg
    typeReg = EntityTypeRegistry.EntityTypeRegistry(FactoryEntityTypes)
  File "H:\work\cyndanera\Projects\toontown\server\otp\level\EntityTypeRegistry.py", line 27, in __init__
    fileLines = file(getPyExtVersion(EntityTypes.__file__)).readlines()
NameError: name 'file' is not defined
:07-20-2023 18:48:00 :task(error): Exception occurred in PythonTask closing-timer-401002936
otp.level.EntityTypeRegistry:21, toontown.coghq.StageRoomBase:23, toontown.coghq.DistributedStageRoomAI:43, direct.distributed.DistributedObjectAI:655, NameError: name 'file' is not defined
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\ai\AIStart.py", line 58, in <module>
    run()
  File "H:\work\cyndanera\Projects\toontown\server\otp\ai\AIBase.py", line 179, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 546, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 497, in step
    self.mgr.poll()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\building\DistributedElevatorExtAI.py", line 144, in elevatorClosedTask
    self.elevatorClosed()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedLawOfficeElevatorExtAI.py", line 28, in elevatorClosed
    lawOfficeZone = self.bldg.createLawOffice(self.lawOfficeId, self.entranceId, players)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\LawOfficeManagerAI.py", line 47, in createLawOffice
    Stage.generateWithRequired(StageZone)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedStageAI.py", line 33, in generate
    room.generateWithRequired(self.zoneId)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedStageRoomAI.py", line 43, in generate
    typeReg = self.getEntityTypeReg()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\StageRoomBase.py", line 23, in getEntityTypeReg
    typeReg = EntityTypeRegistry.EntityTypeRegistry(FactoryEntityTypes)
  File "H:\work\cyndanera\Projects\toontown\server\otp\level\EntityTypeRegistry.py", line 27, in __init__
    fileLines = file(getPyExtVersion(EntityTypes.__file__)).readlines()
NameError: name 'file' is not defined
:07-20-2023 18:48:01 AIBase: __dev__ == True
:07-20-2023 18:48:01 AIBase: __astron__ == True
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:07-20-2023 18:48:02 ToontownAIRepository: Using connect method 'native'
DCFile::read of etc/otp.dc
DCFile::read of etc/toon.dc
:07-20-2023 18:48:02 ToontownAIRepository: Now connecting to 127.0.0.1:7199...
:07-20-2023 18:48:02 ToontownAIRepository: Connecting to gameserver directly (no proxy).
:07-20-2023 18:48:02 ToontownAIRepository: Connecting to //127.0.0.1:7199 via Native interface.
:07-20-2023 18:48:02 ToontownAIRepository: Connected successfully.
:07-20-2023 18:48:02 ToontownAIRepository: Generating district...
:07-20-2023 18:48:02 ToontownAIRepository: Declaring ownership...
:07-20-2023 18:48:02 ToontownAIRepository: Creating local objects...
:07-20-2023 18:48:02 ToontownAIRepository: Creating global objects...
:07-20-2023 18:48:02 ToontownAIRepository: Creating zones...
:07-20-2023 18:48:02 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 2200
:07-20-2023 18:48:02 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 2300
:07-20-2023 18:48:02 DistributedSuitPlannerAI(warning): No front door for building 13 in zone 3200
:07-20-2023 18:48:02 DistributedSuitPlannerAI(warning): No side door for building 13 in zone 3200
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 16 in zone 3300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No front door for building 42 in zone 4100
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 42 in zone 4100
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No front door for building 57 in zone 4100
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 57 in zone 4100
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 19 in zone 4200
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No front door for building 25 in zone 4200
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 25 in zone 4200
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 48 in zone 4300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): Multiple front doors for building 28 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No front door for building 9 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 9 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 10 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 15 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 35 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 36 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 37 in zone 5300
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): Multiple front doors for building 31 in zone 9100
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 31 in zone 9100
:07-20-2023 18:48:03 DistributedSuitPlannerAI: zone 11200 has 2 disconnected suit paths.
:07-20-2023 18:48:03 DistributedSuitPlannerAI: zone 12000 has 6 disconnected suit paths.
:07-20-2023 18:48:03 DistributedSuitPlannerAI: zone 13000 has 5 disconnected suit paths.
[<toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B354EE0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B354F40>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B363130>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B3632E0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B363490>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B363640>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B3637F0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B3639A0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000001B74B363B50>] [golf_kart_0_0, golf_kart_0_1, golf_kart_0_2, golf_kart_1_0, golf_kart_1_1, golf_kart_1_2, golf_kart_2_0, golf_kart_2_1, golf_kart_2_2]
:07-20-2023 18:48:03 WelcomeValleyManagerAI: Creating Welcome Valley zones...
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 22200
:07-20-2023 18:48:03 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 22300
:07-20-2023 18:48:03 ToontownAIRepository: Done.

**Comment by DarthMDev** [comment]
Seems to be a duplicate of #89
