### ISSUE TITLE
Sellbot Factory Crash Missing Unused Model?

### ISSUE THREAD

**Issue by MiloCharmingMagician** [open-toontown/open-toontown#89]
:07-20-2023 14:42:58 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_sellbot_maps.bam: not found on model path (currently: "resources;/h/work/cyndanera/Projects/toontown/server/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")
:07-20-2023 14:42:59 OTPClientRepository: Sending heartbeat mid-frame.
:07-20-2023 14:43:02 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_sellbot_maps.bam: not found on model path (currently: "resources;/h/work/cyndanera/Projects/toontown/server/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")
:07-20-2023 14:43:09 SellbotCogHQLoader: loadPlaceGeom: 11200
:07-20-2023 14:43:09 SellbotHQExterior: Unloading Place (11000). Fsm in final
:07-20-2023 14:43:09 DistributedObject: DistributedSuitPlanner 401002912: disabling
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: defaultShard is 401000001
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: CentralLogger 4688 parent 0 is not defaultShard
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: AstronLoginManager 4670 parent 0 is not defaultShard
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: TTPlayerFriendsManager 4687 parent 0 is not defaultShard
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: TTSpeedchatRelay 4712 parent 0 is not defaultShard
:07-20-2023 14:43:09 OTPClientRepository(warning): dumpAllSubShardObjects: neverDisable set for DistributedInGameNewsMgr 401000006
:07-20-2023 14:43:09 OTPClientRepository: dumpAllSubShardObjects: doIds left: [4688, 4670, 4686, 4687, 4712, 4683, 4695, 4501, 401000001, 100000001, 401000003, 401000005, 401000010, 401000004, 401000009, 401000011, 401000007, 401000008, 401000012, 401000006]
:07-20-2023 14:43:09 DistributedObject: DistributedSuitPlanner 401002913: generating
:07-20-2023 14:43:09 DistributedObject: zone 11200 has 2 disconnected suit paths.
:07-20-2023 14:43:09 DistributedToon: calling LocalAvatar.startchat
:07-20-2023 14:43:09 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_sellbot_maps.bam: not found on model path (currently: "resources;/h/work/cyndanera/Projects/toontown/server/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")
:07-20-2023 14:43:12 :loader(error): Couldn't load file phase_4/models/questmap/cog_hq_sellbot_maps.bam: not found on model path (currently: "resources;/h/work/cyndanera/Projects/toontown/server/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models")
:07-20-2023 14:43:42 DistributedObject: DistributedSuitPlanner 401002913: disabling
:07-20-2023 14:43:42 OTPClientRepository(warning): Server is booting us out (153): The session object with id 100000001 has been unexpectedly deleted.
:07-20-2023 14:43:42 OTPClientRepository(warning): Lost connection to gameserver.
:07-20-2023 14:43:42 FactoryExterior: Unloading Place (11200). Fsm in final
:07-20-2023 14:43:42 OTPClientRepository(warning): unclean exit, abandoning shard
ignoring InputState-forward
:07-20-2023 14:43:42 OTPClientRepository: sending clientLogout
:07-20-2023 14:43:42 LocalAvatar(warning): redundant call to stopUpdateSmartCamera
:07-20-2023 14:43:42 Launcher: New Disconnect Details: 153 - The district you were playing on has been reset.  Everyone who was playing on that district has been disconnected.  However, you should be able to connect again and go right back into the game.
:07-20-2023 14:43:42 OTPClientRepository(warning): Lost connection to server. Notifying user.
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003684 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003685 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003686 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003779 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003781 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003827 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003877 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003924 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 OTPClientRepository(warning): Disable failed. DistObj 401003933 is not in dictionary, ownerView=False
:07-20-2023 14:43:42 :downloader(warning): Windows error code: 0
:07-20-2023 14:43:42 OTPClientRepository(warning): Lost connection to gameserver.
:07-20-2023 14:55:32 OTPClientRepository: Exiting cleanly
:07-20-2023 14:55:32 ToonBase: Exiting Toontown: errorCode = None
:07-20-2023 14:55:32 Launcher: setting panda error code to 0
:07-20-2023 14:55:33 Launcher: Normal exit.
Press any key to continue . . .

**Comment by DarthMDev** [comment]
the top one you can ignore it doesn't really affect the game, street map just doesnt exist for cog hqs
what does the ai show?

**Comment by MiloCharmingMagician** [comment]
> the top one you can ignore it doesn't really affect the game, street map just doesnt exist for cog hqs what does the ai show?

NameError: name 'file' is not defined
:07-20-2023 17:22:53 AIBase: __dev__ == True
:07-20-2023 17:22:53 AIBase: __astron__ == True
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:07-20-2023 17:22:54 ToontownAIRepository: Using connect method 'native'
DCFile::read of etc/otp.dc
DCFile::read of etc/toon.dc
:07-20-2023 17:22:54 ToontownAIRepository: Now connecting to 127.0.0.1:7199...
:07-20-2023 17:22:54 ToontownAIRepository: Connecting to gameserver directly (no proxy).
:07-20-2023 17:22:54 ToontownAIRepository: Connecting to //127.0.0.1:7199 via Native interface.
:07-20-2023 17:22:54 ToontownAIRepository: Connected successfully.
:07-20-2023 17:22:54 ToontownAIRepository: Generating district...
:07-20-2023 17:22:54 ToontownAIRepository: Declaring ownership...
:07-20-2023 17:22:54 ToontownAIRepository: Creating local objects...
:07-20-2023 17:22:54 ToontownAIRepository: Creating global objects...
:07-20-2023 17:22:54 ToontownAIRepository: Creating zones...
:07-20-2023 17:22:54 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 2200
:07-20-2023 17:22:54 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 2300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 13 in zone 3200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 13 in zone 3200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 16 in zone 3300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 42 in zone 4100
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 42 in zone 4100
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 57 in zone 4100
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 57 in zone 4100
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 19 in zone 4200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 25 in zone 4200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 25 in zone 4200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 48 in zone 4300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): Multiple front doors for building 28 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 9 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 9 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 10 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 15 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 35 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 36 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 37 in zone 5300
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): Multiple front doors for building 31 in zone 9100
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 31 in zone 9100
:07-20-2023 17:22:55 DistributedSuitPlannerAI: zone 11200 has 2 disconnected suit paths.
:07-20-2023 17:22:55 DistributedSuitPlannerAI: zone 12000 has 6 disconnected suit paths.
:07-20-2023 17:22:55 DistributedSuitPlannerAI: zone 13000 has 5 disconnected suit paths.
[<toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BE4EE0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BE4F40>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF0130>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF02E0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF0490>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF0640>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF07F0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF09A0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028D05BF0B50>] [golf_kart_0_0, golf_kart_0_1, golf_kart_0_2, golf_kart_1_0, golf_kart_1_1, golf_kart_1_2, golf_kart_2_0, golf_kart_2_1, golf_kart_2_2]
:07-20-2023 17:22:55 WelcomeValleyManagerAI: Creating Welcome Valley zones...
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 22200
:07-20-2023 17:22:55 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 22300
:07-20-2023 17:22:56 ToontownAIRepository: Done.

**Comment by MiloCharmingMagician** [comment]
So what does that mean and how do I fix it?

**Comment by DarthMDev** [comment]
can you show more of the traceback for at the top

**Comment by MiloCharmingMagician** [comment]
sure
:07-20-2023 18:27:45 AIBase: __dev__ == True
:07-20-2023 18:27:45 AIBase: __astron__ == True
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:07-20-2023 18:27:46 ToontownAIRepository: Using connect method 'native'
DCFile::read of etc/otp.dc
DCFile::read of etc/toon.dc
:07-20-2023 18:27:46 ToontownAIRepository: Now connecting to 127.0.0.1:7199...
:07-20-2023 18:27:46 ToontownAIRepository: Connecting to gameserver directly (no proxy).
:07-20-2023 18:27:46 ToontownAIRepository: Connecting to //127.0.0.1:7199 via Native interface.
:07-20-2023 18:27:46 ToontownAIRepository: Connected successfully.
:07-20-2023 18:27:46 ToontownAIRepository: Generating district...
:07-20-2023 18:27:46 ToontownAIRepository: Declaring ownership...
:07-20-2023 18:27:46 ToontownAIRepository: Creating local objects...
:07-20-2023 18:27:46 ToontownAIRepository: Creating global objects...
:07-20-2023 18:27:46 ToontownAIRepository: Creating zones...
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 2200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 2300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 13 in zone 3200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 13 in zone 3200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 16 in zone 3300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 42 in zone 4100
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 42 in zone 4100
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 57 in zone 4100
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 57 in zone 4100
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 19 in zone 4200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 25 in zone 4200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 25 in zone 4200
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 48 in zone 4300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): Multiple front doors for building 28 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No front door for building 9 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 9 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 10 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 15 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 35 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 36 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 37 in zone 5300
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): Multiple front doors for building 31 in zone 9100
:07-20-2023 18:27:47 DistributedSuitPlannerAI(warning): No side door for building 31 in zone 9100
:07-20-2023 18:27:47 DistributedSuitPlannerAI: zone 11200 has 2 disconnected suit paths.
:07-20-2023 18:27:47 DistributedSuitPlannerAI: zone 12000 has 6 disconnected suit paths.
:07-20-2023 18:27:47 DistributedSuitPlannerAI: zone 13000 has 5 disconnected suit paths.
[<toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B53EE0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B53F40>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F130>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F2E0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F490>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F640>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F7F0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5F9A0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x0000028E89B5FB50>] [golf_kart_0_0, golf_kart_0_1, golf_kart_0_2, golf_kart_1_0, golf_kart_1_1, golf_kart_1_2, golf_kart_2_0, golf_kart_2_1, golf_kart_2_2]
:07-20-2023 18:27:47 WelcomeValleyManagerAI: Creating Welcome Valley zones...
:07-20-2023 18:27:48 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 22200
:07-20-2023 18:27:48 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 22300
:07-20-2023 18:27:48 ToontownAIRepository: Done.
exit wait countdown
:07-20-2023 18:28:40 DistributedFactoryAI: generate
:07-20-2023 18:28:40 DistributedFactoryAI: start factory 11500 401003894 creation, frame=1274
:07-20-2023 18:28:40 DistributedFactoryAI: loading spec
:07-20-2023 18:28:40 DistributedFactoryAI: creating entity type registry
Traceback (most recent call last):
  File "H:\work\cyndanera\Projects\toontown\server\toontown\building\DistributedElevatorExtAI.py", line 144, in elevatorClosedTask
    self.elevatorClosed()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedFactoryElevatorExtAI.py", line 28, in elevatorClosed
    factoryZone = self.bldg.createFactory(self.factoryId, self.entranceId, players)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\FactoryManagerAI.py", line 22, in createFactory
    factory.generateWithRequired(factoryZone)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedFactoryAI.py", line 36, in generate
    typeReg = self.getEntityTypeReg()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\FactoryBase.py", line 26, in getEntityTypeReg
    typeReg = EntityTypeRegistry.EntityTypeRegistry(FactoryEntityTypes)
  File "H:\work\cyndanera\Projects\toontown\server\otp\level\EntityTypeRegistry.py", line 27, in __init__
    fileLines = file(getPyExtVersion(EntityTypes.__file__)).readlines()
NameError: name 'file' is not defined
:07-20-2023 18:28:41 :task(error): Exception occurred in PythonTask closing-timer-401002914
otp.level.EntityTypeRegistry:21, toontown.coghq.FactoryBase:26, toontown.coghq.DistributedFactoryAI:36, direct.distributed.DistributedObjectAI:655, NameError: name 'file' is not defined
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\ai\AIStart.py", line 58, in <module>
    run()
  File "H:\work\cyndanera\Projects\toontown\server\otp\ai\AIBase.py", line 179, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 546, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 497, in step
    self.mgr.poll()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\building\DistributedElevatorExtAI.py", line 144, in elevatorClosedTask
    self.elevatorClosed()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedFactoryElevatorExtAI.py", line 28, in elevatorClosed
    factoryZone = self.bldg.createFactory(self.factoryId, self.entranceId, players)
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\FactoryManagerAI.py", line 22, in createFactory
    factory.generateWithRequired(factoryZone)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 399, in generateWithRequired
    self.generate()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\DistributedFactoryAI.py", line 36, in generate
    typeReg = self.getEntityTypeReg()
  File "H:\work\cyndanera\Projects\toontown\server\toontown\coghq\FactoryBase.py", line 26, in getEntityTypeReg
    typeReg = EntityTypeRegistry.EntityTypeRegistry(FactoryEntityTypes)
  File "H:\work\cyndanera\Projects\toontown\server\otp\level\EntityTypeRegistry.py", line 27, in __init__
    fileLines = file(getPyExtVersion(EntityTypes.__file__)).readlines()
NameError: name 'file' is not defined
:07-20-2023 18:28:41 AIBase: __dev__ == True
:07-20-2023 18:28:41 AIBase: __astron__ == True
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:07-20-2023 18:28:42 ToontownAIRepository: Using connect method 'native'
DCFile::read of etc/otp.dc
DCFile::read of etc/toon.dc
:07-20-2023 18:28:42 ToontownAIRepository: Now connecting to 127.0.0.1:7199...
:07-20-2023 18:28:42 ToontownAIRepository: Connecting to gameserver directly (no proxy).
:07-20-2023 18:28:42 ToontownAIRepository: Connecting to //127.0.0.1:7199 via Native interface.
:07-20-2023 18:28:42 ToontownAIRepository: Connected successfully.
:07-20-2023 18:28:42 ToontownAIRepository: Generating district...
:07-20-2023 18:28:42 ToontownAIRepository: Declaring ownership...
:07-20-2023 18:28:42 ToontownAIRepository: Creating local objects...
:07-20-2023 18:28:42 ToontownAIRepository: Creating global objects...
:07-20-2023 18:28:42 ToontownAIRepository: Creating zones...
:07-20-2023 18:28:42 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 2200
:07-20-2023 18:28:42 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 2300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 13 in zone 3200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 13 in zone 3200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 16 in zone 3300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 42 in zone 4100
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 42 in zone 4100
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 57 in zone 4100
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 57 in zone 4100
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 19 in zone 4200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 25 in zone 4200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 25 in zone 4200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 48 in zone 4300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): Multiple front doors for building 28 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 9 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 9 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 10 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 15 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 35 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 36 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 37 in zone 5300
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): Multiple front doors for building 31 in zone 9100
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 31 in zone 9100
:07-20-2023 18:28:43 DistributedSuitPlannerAI: zone 11200 has 2 disconnected suit paths.
:07-20-2023 18:28:43 DistributedSuitPlannerAI: zone 12000 has 6 disconnected suit paths.
:07-20-2023 18:28:43 DistributedSuitPlannerAI: zone 13000 has 5 disconnected suit paths.
[<toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C54EE0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C54F40>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C62130>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C622E0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C62490>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C62640>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C627F0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C629A0>, <toontown.safezone.DistributedGolfKartAI.DistributedGolfKartAI object at 0x000002CD61C62B50>] [golf_kart_0_0, golf_kart_0_1, golf_kart_0_2, golf_kart_1_0, golf_kart_1_1, golf_kart_1_2, golf_kart_2_0, golf_kart_2_1, golf_kart_2_2]
:07-20-2023 18:28:43 WelcomeValleyManagerAI: Creating Welcome Valley zones...
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No side door for building 39 in zone 22200
:07-20-2023 18:28:43 DistributedSuitPlannerAI(warning): No front door for building 36 in zone 22300
:07-20-2023 18:28:44 ToontownAIRepository: Done.

**Comment by DarthMDev** [comment]
looks like an import issue we need to fix in EntityTypeRegistry file

**Comment by MiloCharmingMagician** [comment]
Also the other factorys, estate, field office crash too
and toon doesn't say anything when using speedchat+

**Comment by MiloCharmingMagician** [comment]
> looks like an import issue we need to fix in EntityTypeRegistry file

what do you mean  EntityTypeRegistry file??

**Comment by DarthMDev** [comment]
yes as a lot of stuff is unfinished

**Comment by DarthMDev** [comment]
> > looks like an import issue we need to fix in EntityTypeRegistry file
> 
> what do you mean EntityTypeRegistry file??

its in the traceback , its a python file

**Comment by MiloCharmingMagician** [comment]
> 

I tried fixing it

from panda3d.core import *
from direct.directnotify import DirectNotifyGlobal
import types
from otp.level import AttribDesc
from otp.level import EntityTypeDesc
from direct.showbase.PythonUtil import mostDerivedLast
import os
import string
import importlib

class EntityTypeRegistry:
    notify = DirectNotifyGlobal.directNotify.newCategory('EntityTypeRegistry')

    def __init__(self, entityTypeModule):
        self.entTypeModule = entityTypeModule
        hv = HashVal()
        from otp.level import EntityTypes
        importlib.reload(EntityTypes)
        importlib.reload(self.entTypeModule)

        def getPyExtVersion(filename):
            base, ext = os.path.splitext(filename)
            if ext == '.pyc' or ext == '.pyo':
                filename = base + '.py'
            return filename

        fileLines = file(getPyExtVersion(EntityTypes.__file__)).readlines()
        hv.hashString(string.join(fileLines, ''))
        s = str(hv.asHex())
        s += '.'
        fileLines = file(getPyExtVersion(self.entTypeModule.__file__)).readlines()
        hv.hashString(string.join(fileLines, ''))
        s += str(hv.asHex())
        self.hashStr = s
        getPyExtVersion = None
        classes = []
        for key, value in list(entityTypeModule.__dict__.items()):
            if type(value) is type:
                if issubclass(value, EntityTypeDesc.EntityTypeDesc):
                    classes.append(value)

        self.entTypeName2typeDesc = {}
        mostDerivedLast(classes)
        for c in classes:
            if 'type' in c.__dict__:
                if c.type in self.entTypeName2typeDesc:
                    EntityTypeRegistry.notify.debug("replacing %s with %s for entity type '%s'" % (self.entTypeName2typeDesc[c.type].__class__, c, c.type))
                self.entTypeName2typeDesc[c.type] = c()

        self.output2typeNames = {}
        for typename, typeDesc in list(self.entTypeName2typeDesc.items()):
            if typeDesc.isConcrete():
                if hasattr(typeDesc, 'output'):
                    outputType = typeDesc.output
                    self.output2typeNames.setdefault(outputType, [])
                    self.output2typeNames[outputType].append(typename)

        self.permanentTypeNames = []
        for typename, typeDesc in list(self.entTypeName2typeDesc.items()):
            if typeDesc.isPermanent():
                self.permanentTypeNames.append(typename)

        self.typeName2derivedTypeNames = {}
        for typename, typeDesc in list(self.entTypeName2typeDesc.items()):
            typenames = []
            for tn, td in list(self.entTypeName2typeDesc.items()):
                if td.isConcrete():
                    if issubclass(td.__class__, typeDesc.__class__):
                        typenames.append(tn)

            self.typeName2derivedTypeNames[typename] = typenames

        return

    def getAllTypeNames(self):
        return list(self.entTypeName2typeDesc.keys())

    def getTypeDesc(self, entTypeName):
        return self.entTypeName2typeDesc[entTypeName]

    def getTypeNamesFromOutputType(self, outputType):
        return self.output2typeNames.get(outputType, [])

    def getDerivedTypeNames(self, entTypeName):
        return self.typeName2derivedTypeNames[entTypeName]

    def isDerivedAndBase(self, entType, baseEntType):
        return entType in self.getDerivedTypeNames(baseEntType)

    def getPermanentTypeNames(self):
        return self.permanentTypeNames

    def getHashStr(self):
        return self.hashStr

    def __hash__(self):
        return hash(repr(self))

    def __repr__(self):
        return str(self.entTypeName2typeDesc)

**Comment by MiloCharmingMagician** [comment]
> > > looks like an import issue we need to fix in EntityTypeRegistry file
> > 
> > 
> > what do you mean EntityTypeRegistry file??
> 
> its in the traceback , its a python file

Do you know what's wrong? I tried to fix it didn't work out.

**Comment by DarthMDev** [comment]
ill probably look at it at some point and do a pr if littlecat doesnt

**Comment by MiloCharmingMagician** [comment]
Can't seem to go into field offices either

**Comment by MiloCharmingMagician** [comment]
> ill probably look at it at some point and do a pr if littlecat doesnt

the game is pretty much unplayable if no cog buildings, bosses, field offices, factories, estate, speedchat+, work

**Comment by DarthMDev** [comment]
Weird field offices seem to work fine on my end  and this is on the latest develop branch
Same with cog buildings
